### ISSUE TITLE
`IndexError` in `has_multiple_children`

### ISSUE THREAD

**Issue by The-Compiler** [akissinger/dodo#94]
Dodo just crashed for me after sending a mail. Not sure which parts of the log are related as there are no timestamps:

```
Processed 7 total files in almost no time.
Added 1 new message to the database.
Folder Sent [acc: uberspace]:
 Syncing Sent: IMAP -> Maildir
 Copy message UID -2 (1/2) local:Sent -> remote:Sent
 Copy message UID -1 (2/2) local:Sent -> remote:Sent
Folder sent [acc: uberspace]:
 Syncing sent: IMAP -> Maildir
[...]
Folder spam [acc: uberspace]:
 Syncing spam: IMAP -> Maildir
Error opening /home/florian/mail/Sent/new/1733838287.M811583P195996Q6.fawkes:2,S: No such file or directory
```

followed by:

```pytb
Traceback (most recent call last):
  File "/home/florian/proj/dodo/dodo/panel.py", line 84, in focusInEvent
    self.refresh()
  File "/home/florian/proj/dodo/dodo/thread.py", line 623, in refresh
    self.model.refresh()
  File "/home/florian/proj/dodo/dodo/thread.py", line 316, in refresh
    roots = self.compute_roots(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/dodo/dodo/thread.py", line 290, in compute_roots
    return make_thread_trees(raw_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/dodo/dodo/thread.py", line 243, in make_thread_trees
    if has_multiple_children(raw_thread_data):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/dodo/dodo/thread.py", line 241, in has_multiple_children
    forest = forest[0][1]
             ~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by The-Compiler** [comment]
I added a

```diff
diff --git i/dodo/thread.py w/dodo/thread.py
index 5ad4a33..63df4d6 100644
--- i/dodo/thread.py
+++ w/dodo/thread.py
@@ -238,7 +238,12 @@ def make_thread_trees(raw_thread_data: list) -> list[ThreadItem]:
         while forest:
             if len(forest) > 1:
                 return True
-            forest = forest[0][1]
+
+            try:
+                forest = forest[0][1]
+            except IndexError:
+                print(raw_thread_data)
+                raise
 
     if has_multiple_children(raw_thread_data):
         return [ThreadItem(root, None) for root in raw_thread_data]
```

and could just reproduce it again:

```
Error opening /home/florian/mail/INBOX/new/1733840329_0.537182.fawkes,U=104872,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,: No such file or directory
[[[]]]
```

I think it might be happening when opening a mail between the point where `offlineimap` did run and move the file to `~/mail/INBOX/cur/1733840329_0.537182.fawkes,U=104872,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S`, but before `notmuch new` was run?
